// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/farwydi/thunderstorm/domain"
	"github.com/farwydi/thunderstorm/endpoint/webhook"
	"github.com/farwydi/thunderstorm/gateway/statedriver"
)

// Injectors from wire.go:

func setup(config domain.Config) (application, func(), error) {
	stateDriverGateway := statedriver.NewStateDriverGateway()
	txTable := NewBasic()
	stateMachine := domain.NewStateMachine(stateDriverGateway, txTable)
	handler := webhook.NewRouter(config, stateMachine)
	mainApplication := newApplication(handler)
	return mainApplication, func() {
	}, nil
}
